TERM_CMD_DEF(0x01, ECHO,                        echo_handler)
TERM_CMD_DEF(0x02, SET_RTC,                     set_rtc)
TERM_CMD_DEF(0x03, SET_ARR,                     set_arr)
TERM_CMD_DEF(0x04, SET_CCR,                     set_ccr)
TERM_CMD_DEF(0x05, SET_ANGLE,                   set_angle)
TERM_CMD_DEF(0x06, GET_ANGLE,                   get_angle)